name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-ui5-versions:
    name: Check UI5 versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check UI5 versions
        id: check-ui5
        uses: DevEpos/check-outdated-ui5-version@v0
        with:
          manifestPaths: |
            app/**/webapp


