name: Fix outdated UI5 versions

on:
  workflow_dispatch:

jobs:
  fix-ui5-versions:
    name: Update UI5 versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Update UI5 versions
        id: check-ui5
        uses: DevEpos/check-outdated-ui5-version@v1
        with:
          fixOutdated: true
          manifestPaths: |
            app/**/webapp

      - name: Create Pull Request
        if: ${{ steps.check-ui5.outputs.modifiedFiles != '' }}
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update outdated UI5 versions"
          branch: "update-ui5-versions/patch"
          title: "Update Outdated UI5 Versions"
          add-paths: ${{ steps.check-ui5.outputs.modifiedFiles }}
          body: |
            This pull request updates the outdated UI5 versions found in the following files:

            ```
            ${{ steps.check-ui5.outputs.modifiedFiles }}
            ```

            ${{ steps.check-ui5.outputs.summary}}
            
